version: '3.7'
services:
  mongo:
    image: mongo
    #restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: bookstore
      MONGO_INITDB_USERNAME: user
      MONGO_INITDB_PASSWORD: user
      MONGO_INITDB_DATABASE_COLLECTION: users
    volumes:
      - ./data/db:/data/db
      - ./data/log:/var/log
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    healthcheck:
      test: [ "CMD", "mongosh", "localhost:27017/bookstore", "--eval", "'db.runCommand(\"ping\").ok'" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    command: mongod --quiet --logpath dev/null
     
  mongo-express:
    image: mongo-express
    #restart: always
    ports:
      - 8081:8081
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_DATABASE: bookstore







